name: Semver release

on: workflow_dispatch

jobs:
  semver:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set correct Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Create Github App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.KOWABUNGA_BOT_APP_ID }}
          private-key: ${{ secrets.KOWABUNGA_BOT_PRIVATE_KEY }}

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25.0.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
